title: The Furrier Transform
author: PandamusRex
email: allen@allensnook.com
theme: minima
description: Furries | Motorcycling | Electric Vehicles | Dark Electronic Music | Wireless IoT | Mobile Engineering | All Things Apple | PFP by AngieWolf
show_excerpts: true
exclude: [tmp/,vendor/,Gemfile,Gemfile.lock]
sass:
  sass_dir: _sass
google_analytics: UA-13130172-1
twitter_username: pandamusrex
flickr_username: allenreloaded
instagram_username: pandamusrex
rss: rss
